server:
  port: 8001
spring:
  application:
    name: consumer-service #应用/微服务名字
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务器地址
        username: nacos
        password: nacos
dubbo: #dubbo与nacos的通信配置
  application:
    name: consumer-dubbo  #consumer在Nacos中的应用id
  registry:
    address: nacos://localhost:8848
