server:
  port: 9001
spring:
  application:
    name: producer-service #应用/微服务名字
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务器地址
        username: nacos #用户名密码
        password: nacos
dubbo: #dubbo与nacos的通信配置
  application:
    name: producer-dubbo #producer在Nacos中的应用id
  registry: #Provider与Nacos通信地址，与spring.cloud.nacos地址一致
    address: nacos://localhost:8848
  protocol:
    name: dubbo #通信协议名
    port: 20880 #配置通信端口，默认为20880
  scan:
    base-packages: com.zjq.producerservice.dubbo
